# dynamic configurations (change from run to run)
- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction:
      - mean
      - 1
    endmember_normalisation: false
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  simulation:
    type: "spread"
    N: 100
    Rb_vals: [0,1]
    n_depths: 10
    depth_lims: [0, 10]
    n_ks: 10
    k_lims: [0, 0.4]
    n_bbs: 10
    bb_lims: [0.01, 0.03]
    n_noise_levels: 10
    noise_lims: [0.001, 0]
    noise_ind: 0  # TODO: remove unnecessary noise vars
  fitting:
    objective_fn: r2
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-9

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: r2
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: euclidean_distance
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: spectral_angle_w1
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3


- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: spectral_similarity_gradient
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: mahalanobis_distance  # DIDN'T WORK
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: spectral_information_divergence
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3
      
-
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: sidsam
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3
      
-
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: jmsam
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3
      

