# dynamic configurations (change from run to run)
- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: spectral_angle
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: r2
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: euclidean_distance
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: spectral_angle_w1
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3


- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: spectral_similarity_gradient
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: mahalanobis_distance  # DIDN'T WORK
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: spectral_information_divergence
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3
      
-
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: sidsam
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3
      
-
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_type: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: jmsam
    bb_bounds:
      - 0
      - 0.4
    Kd_bounds:
      - 0
      - 0.4
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3
      

