# dynamic configurations (change from run to run)
- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    # endmember_source: data/AOP_models/Rb_model_single_coefficient.txt
    endmember_source: 'spectral_library'
    endmember_dimensionality_reduction: mean
    endmember_normalisation: false
    endmember_class_schema: three_endmember
    spectra_normalisation: false
  simulation:
    type: "spread"
    N: 1000
    Rb_vals: [1, 0.2, 0]
    n_depths: 10
    depth_lims: [0, 16.8]
    n_ks: 10
    k_lims: [0.01688, 3.17231]
    n_bbs: 10
    bb_lims: [0, 0.41123]
    n_noise_levels: 10
    noise_lims: [0.001, 0]
    noise_ind: 0  # TODO: remove unnecessary noise vars
  fitting:
    objective_fn: r2
    Rb_init: 0
    bb_bounds:
      - 0
      - 0.41123
    Kd_bounds:
      - 0.01688
      - 3.17231
    H_bounds:
      - 0
      - 30
    endmember_bounds:
      - 0
      - np.inf
    solver: Nelder-Mead
    tol: 1e9

- 
  processing:
    aop_group_num: 1
    nir_wavelengths:
      - 750
      - 1100
    sensor_range:
      - 450
      - 690
    endmember_dimensionality_reduction: mean
    endmember_normalisation: minmax
    endmember_class_schema: inorganic_organic
    spectra_normalisation: false
  fitting:
    objective_fn: r2
    bb_bounds:
      - 0
      - 0.41123
    Kd_bounds:
      - 0.01688
      - 3.17231
    H_bounds:
      - 0
      - 30
    solver: Nelder-Mead
    tol: 1e-3
